# Generated by Django 5.2.8 on 2025-11-26 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Energyapp', '0002_colorizedimage_grayscaleimage_resizedimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grayscaleimage',
            name='image',
            field=models.ImageField(upload_to='uploaded_images/'),
        ),
        migrations.CreateModel(
            name='YOLOOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yolo_outputs/')),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Energyapp.grayscaleimage')),
            ],
        ),
        migrations.DeleteModel(
            name='ColorizedImage',
        ),
    ]
