# Generated by Django 5.2.8 on 2025-11-28 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Energyapp', '0003_alter_grayscaleimage_image_yolooutput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grayscaleimage',
            name='capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grayscaleimage',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grayscaleimage',
            name='sunlight_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yolooutput',
            name='loss_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yolooutput',
            name='total_daily_loss_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yolooutput',
            name='total_panels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PanelAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_number', models.IntegerField()),
                ('panel_loss_kwh', models.FloatField()),
                ('yolo_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='Energyapp.yolooutput')),
            ],
        ),
        migrations.CreateModel(
            name='FaultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_name', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('affected_area', models.FloatField()),
                ('loss_percentage', models.FloatField()),
                ('daily_loss', models.FloatField()),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='Energyapp.panelanalysis')),
            ],
        ),
    ]
